In [2]:
import numpy as np

## Create Numpy Arrays from Python Lists

In [3]:
np.array([1, '2', 3, 4])

array(['1', '2', '3', '4'], dtype='<U21')

In [4]:
np.array([1, 2, 3, 4], dtype='str')

array(['1', '2', '3', '4'], dtype='<U1')

In [5]:
a = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
])

In [6]:
a.shape

(3, 4)

In [7]:
a.ndim

2

In [8]:
a.size

12

In [9]:
a.dtype

dtype('int64')

## Create Numpy Array from Scratch

### zeros, ones, full, arange, linspace

In [10]:
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones([2, 4], dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.full([2, 4], 4, dtype = int)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [13]:
# Create an array filled with a linear sequence
# Starting at "start", ending at "stop", stepping by "step"
# this is similar to the built-in range() function

start = 0
stop = 20
step = 2.4
np.arange(start, stop, step, dtype = float)

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. , 14.4, 16.8, 19.2])

In [14]:
# Create an array of n values evenly spaced between a and b
a = 0
b = 1
n = 11
np.linspace(a, b, n)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Random

In [34]:
# seed for reproducibility (not changes)
np.random.seed(102313)

np.random.random((4, 4))

array([[0.93819399, 0.19829302, 0.09352922, 0.25648774],
       [0.8703365 , 0.53660967, 0.35515794, 0.62497085],
       [0.17007802, 0.06170197, 0.25195389, 0.88938289],
       [0.24426505, 0.56336841, 0.98629837, 0.17642677]])

In [43]:
np.random.normal(0, 0.5, (3, 3))

array([[-0.31829635,  0.18467901,  0.03882313],
       [ 0.20367413,  0.60259046,  0.42285843],
       [-0.62274093,  0.01163001,  0.57736912]])

In [45]:
np.random.randint(0, 10, (4, 5))

array([[5, 0, 0, 8, 4],
       [3, 3, 9, 8, 1],
       [2, 5, 3, 3, 6],
       [7, 9, 0, 1, 4]])

In [46]:
np.random.rand(4, 4)

array([[0.88880226, 0.31657727, 0.88547673, 0.89496036],
       [0.10130168, 0.6293991 , 0.4181791 , 0.14725755],
       [0.13511296, 0.46372474, 0.63672856, 0.83076665],
       [0.71496981, 0.00731501, 0.19607685, 0.47657446]])

## Array Indexing & Slicing