In [13]:
import numpy as np

## Create Numpy Arrays from Python Lists

In [14]:
np.array([1, '2', 3, 4])

array(['1', '2', '3', '4'], dtype='<U21')

In [15]:
np.array([1, 2, 3, 4], dtype='str')

array(['1', '2', '3', '4'], dtype='<U1')

In [16]:
a = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
])

In [18]:
a.shape

(3, 4)

In [19]:
a.ndim

2

In [20]:
a.size

12

In [22]:
a.dtype

dtype('int64')

## Create Numpy Array from Scratch

### zeros, ones, full, arange, linspace

In [31]:
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
np.ones([2, 4], dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.full([2, 4], 4, dtype = int)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [47]:
# Create an array filled with a linear sequence
# Starting at "start", ending at "stop", stepping by "step"
# this is similar to the built-in range() function

start = 0
stop = 20
step = 2.4
np.arange(start, stop, step, dtype = float)

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. , 14.4, 16.8, 19.2])

In [46]:
# Create an array of n values evenly spaced between a and b
a = 0
b = 1
n = 11
np.linspace(a, b, n)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Random